#!/bin/bash
image="$1"
docker run -it --rm --privileged=true \
	-v $(pwd)/images:/usr/rpi/images -w /usr/rpi \
	--detach \
	ryankurte/docker-rpi-emu \
	/bin/bash -c \
	'qemu-system-arm   \
		-cpu arm1176   -m 256   -M versatilepb -no-reboot  \
		-append "root=/dev/sda2 panic=1 rw loglevel=8 console=ttyAMA0,115200" \
		-kernel images/kernel-qemu-4.4.34-jessie \
		-drive file=/usr/rpi/images/'"${image}"',index=0,media=disk,format=raw \
		-net nic -net user,restrict=off \
		-nographic'
