#!/bin/bash
APPEND_ARGS="root=/dev/sda2 panic=1 rw loglevel=8 console=ttyAMA0,115200 $@"
qemu-system-arm   -cpu arm1176   -m 256   -M versatilepb \
	-no-reboot   -serial stdio   \
	-append "${APPEND_ARGS}" \
	-kernel kernel/kernel-qemu-4.4.34-jessie \
	-net nic -net user,restrict=off  \
	-drive file=$(pwd)/images/hypriotos-rpi-v1.1.3.img,index=0,media=disk,format=raw
