#!/bin/bash

while getopts "k:i:n:s:t:x" opt; do
  case $opt in
    i)  image_arg="-i $OPTARG" ; image="$OPTARG" ; echo image = ${OPTARG} ;;
    k)  kernel_arg="-k $OPTARG" ; echo kernel = ${OPTARG} ;;
	s)	size_arg="-s $OPTARG" ; echo size = ${OPTARG} ;;
	n)  hostname_arg="-n $OPTARG" ; echo hostname = ${OPTARG} ;;
	t)  target_dir_arg="-t $OPTARG" ; echo target dir = ${OPTARG} ;;
	x)  overwrite_arg="-x" ; echo overwrite target image if needed ;;
    \? ) echo "Unknown option: -$OPTARG" >&2; exit 1;;
    :  ) echo "Missing option argument for -$OPTARG" >&2; exit 1;;
    *  ) echo "Unimplemented option: -$OPTARG" >&2; exit 1;;
    esac
done

#shift $(($OPTIND - 1))

# delegating parameter validation to sub scripts

# if [ "$image" == "" ] #&& [[ -d $1 ]]
# then
#     echo "-i must be used to set which image to run" >&2
#     exit 1
# fi


# if [[ "$hostname" == "" ]]
# then
#     echo "-n must be used to define container name" >&2
#     exit 1
# fi

# if [[ "$kernel" == "" ]]
# then
#     echo "-k must be used to define kernel to run image" >&2
#     exit 1
# fi

# if [ ! -f ${image} ]; then
# 	echo "Image file \"$image\" does not exist"
# 	exit 2
# fi

# if [ ! -f ${kernel} ]; then
# 	echo "Kernel file \"$kernel\" does not exist"
# 	exit 2
# fi

cd $(dirname $0)
mkdir -p /tmp/images
set set -x 
container_img=$($(dirname $0)/scripts/prepare-hypriot-qemu/prepare_for_qemu ${target_dir_arg} ${hostname_arg} ${image_arg} ${size_arg} ${overwrite_arg} | tail -1)
./emulate-hypriot-nohead -i "${container_img}" "${kernel_arg}"
